@SurveyMaker.API_HostAddress = http://localhost:5001
@AccessToken = CfDJ8N2VOELTeDlKnscwD3HokgrO-vojEMJ2RGO8Nt-8LsjOLXmOfhZcarMdVSWLFLxmt6tfgBaCTGGTzVGdo3Q9TZQeKOv_2Z58mV-aqAwZdvS4PQa1gjmt3vTrVTxN2swX8qKZr78f4NNGjsylyVflpEF8Z03Otpel9cuX2W0PJ5dn9G4gl-te09ovbHHNj5UdMJ8dGSjdxI2uOYAgtM9_J-MdIjg7dtYekgrNJ9mITQlR6Fq63sdNvhL3WQmuHLAlgFMu6rOZj8Lpqv13YPVP09QZC3dW6fBI3HVG5gZRmKClbFRh3k4KEU91aiqmEL5Mke089ty0ZhN6Hr5oVOlw1BOSB4LsWbcH2s-UqFp_cU4pjvktFDBNS9MqMf2tNaHn8-vh-KMcYtCbcsR8hHKGW6sN6D8YYVxaQr44E_mwUT3DM8SVG73zXP4c2mWmqc5q16MekbZgi8p9rgxLArMpi6QEBtETaGn6TQJn1Iu2ISpPd9QgIKJrdlGy0f4AKZ5uk8pNCY8bcMfN4TrC3jdE0qC92HzEjBuRLxtJnXCMD3ae22r9bz_l4MPYJik0UbPmDLK0ZQmhSpPLlfO52ubbit1jjdnQI8iM-rmM2nj4oSm_8zBbBJnRoN9QpnaqOgHVrdYl1_zK4rdmA4WTeT8JqSBWQbFFT_rOLf-0hgQxjrqY-mwjJ6259PdsEGyw4o23uA

### Register
POST {{SurveyMaker.API_HostAddress}}/Register
Accept: application/json
Content-Type: application/json
{
  "email": "email@email.com",
  "firstName": "TestName",
  "lastName": "TestLastName",
  "password": "MyPassword123.",
  "phoneNumber": "1234567"
}

### Login
# @name loginResponse
POST {{SurveyMaker.API_HostAddress}}/Login
Accept: application/json
Content-Type: application/json
{
  "email": "email@email.com",
  "password": "MyPassword123."
}

### Public test endpoint
GET {{SurveyMaker.API_HostAddress}}/Test/Public
Accept: application/json

### Private test endpoint
GET {{SurveyMaker.API_HostAddress}}/Test/Private
Authorization: Bearer {{AccessToken}}
Accept: application/json
